name: randnum workshop
on:
  push:
    tags:
    - "v*"
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/randnum-cicd:${{ github.ref_name }}
      - 
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: ${{ env.Name }}\nMatriculation: ${{ env.mat_no }}\nEmail: ${{ env.email }}\nRepo: ${{ github.repositoryUrl }}\nImage name: ${{ secrets.DOCKER_HUB_USERNAME }}/randnum-cicd:${{ github.ref_name }}\nImage URL: https://hub.docker.com/repository/docker/${{ secrets.DOCKER_HUB_USERNAME }}/randnum-cicd"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          name: ${{ secrets.NAME }}
          mat_no: ${{ secrets.MATRICULATION_NUMBER }}
          email: ${{ secrets.EMAIL }}

